name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-github-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@enfiy'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build:prod
        
      - name: Bundle
        run: npm run bundle:prod
        
      - name: Debug workflow context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Token starts with: $(echo ${{ secrets.GITHUB_TOKEN }} | cut -c1-10)..."
          whoami
        
      - name: Create .npmrc
        run: |
          cat > ~/.npmrc << EOF
          @enfiy:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          EOF
          cat ~/.npmrc
        
      - name: Test authentication
        run: npm whoami --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}